version: '3.8'

services:
  frontend:
    build: .
    environment:
      - BACKEND_URL=https://127.0.0.1:8443
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs:ro
volumes:
  certs:
