version: '3.8'

services:
  frontend:
    container_name: vereinskasse-frontend
    environment:
      - BACKEND_URL=https://deine-server-ip:8443
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Wir spiegeln den lokalen Ordner ./certs-frontend in den Container
      - ./certs:/etc/nginx/certs
