server {
    listen 80;
    server_name localhost;
    return 301 https://$host$request_uri; # HTTP zu HTTPS umleiten
}

server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/certs/cert.pem;
    ssl_certificate_key /etc/nginx/certs/key.pem;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html; # Wichtig für Vue-Router!
    }

    # Proxy für API-Anfragen zum Backend
    location /api {
        proxy_pass https://backend-container:8443;
        proxy_ssl_verify off; # Da selbstsigniert
    }

    location /auth {
        proxy_pass https://backend-container:8443;
        proxy_ssl_verify off;
    }
}